
# ********** LOGIN ************ # 
###  LOGIN
POST {{baseUrl}}/login
content-type: application/json
Authorization: Bearer {{token}}

{
    "email": "p.cox@outlook.com",
    "password": "Password123!"
}
