
# ********** REGISTER ************ # 

###  REGISTER
POST {{baseUrl}}/registration
content-type: application/json

{
    "firstName": "Peter",
    "lastName": "Cox",
    "username": "peterssssssdddsdsscox",
    "email": "p.cox@outlsdssffffdsdofffokkkk.com",
    "password": "Password123!"
}
