
# ********** SUBTASKS ************ # 

###  GET SUBTASKS
GET {{baseUrl}}/tasklists/5/tasks/29/subtasks 
content-type: application/json
Authorization: Bearer {{token}}

### GET SUBTASK BY ID
GET http://localhost:5000/api/tasklists/5/tasks/29/subtasks/4 
content-type: application/json

### CREATE SUBTASK
POST http://localhost:5000/api/tasklists/5/tasks/29/subtasks 
content-type: application/json

{
	"title": "Subtask #444",
}

### UPDATE SUBTASK
PUT http://localhost:5000/api/tasklists/1/tasks/3/subtasks/2 
content-type: application/json

{
	"id": 2,
	"title": "UPDATED TASK",
	"completed": true
}

### DELETE SUBTASK
DELETE http://localhost:5000/api/tasklists/5/tasks/29/subtasks/4


