# ********** TASKLISTS ************ # 

###  GET TASK LISTS
GET {{baseUrl}}/tasklists 
content-type: application/json
Authorization: Bearer {{token}}

### GET TASK LIST BY ID
GET {{baseUrl}}/tasklists/8
content-type: application/json
Authorization: Bearer {{token}}

### CREATE TASKLIST
POST {{baseUrl}}/tasklists
content-type: application/json
Authorization: Bearer {{token}}

{
	"title": "New Tasklist",
}

### UPDATE TASKLIST
PATCH {{baseUrl}}/tasklists/8
content-type: application/json
Authorization: Bearer {{token}}

[
  {
    "op": "add",
    "path": "/title",
    "value": "JSON PATCH WORKED!"
  }
]

### DELETE TASKLIST
DELETE {{baseUrl}}/tasklists/10
Authorization: Bearer {{token}}


