
# ********** TASKS ************ # 

###  GET TASKS
GET http://localhost:5000/api/tasklists/9/tasks 
content-type: application/json

### GET TASK BY ID
GET http://localhost:5000/api/tasklists/4/tasks/12
content-type: application/json

### CREATE TASK
POST http://localhost:5000/api/tasklists/9/tasks 
content-type: application/json

{
	"title": "Yet another thing to do",
}

### UPDATE TASK
PUT http://localhost:5000/api/tasklists/4/tasks/10 
content-type: application/json

{
	"title": "UPDATED TASK",
}

### DELETE TASK
DELETE http://localhost:5000/api/tasklists/4/tasks/8 


