# ********** TASKS ************ # 

###  GET TASKS
GET {{baseUrl}}/tasklists/5/tasks 
content-type: application/json
Authorization: Bearer {{token}}

### GET TASK BY ID
GET {{baseUrl}}/tasklists/9/tasks/19
content-type: application/json
Authorization: Bearer {{token}}

### CREATE TASK
POST {{baseUrl}}/tasklists/9/tasks 
content-type: application/json
Authorization: Bearer {{token}}

{
	"title": "NO due date?",
}

### UPDATE TASK
PATCH {{baseUrl}}/tasklists/9/tasks/19
content-type: application/json
Authorization: Bearer {{token}}

[
  {
    "op": "add",
    "path": "/title",
    "value": "BOB MARLEY!"
  },
  {
    "op": "add",
    "path": "/isImportant",
    "value": true
  },
   {
    "op": "add",
    "path": "/dueDate",
    "value": "2023-06-13T01:29:51.022Z"
  }
]

### DELETE TASK
DELETE {{baseUrl}}/tasklists/4/tasks/8 


