
# ********** TASKLISTS ************ # 

@baseUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicGV0ZXJjb3giLCJqdGkiOiI3ZWRhZmVlNC1kMTFlLTQ0YjYtYjc4Ni0zNGZmYWQ1N2Y3MzAiLCJleHAiOjE2ODY2MDI2NDQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MjQyODgiLCJhdWQiOiJodHRwOiAvL2xvY2FsaG9zdDo0MjAwIn0.ONuL4xWnkdn3aHxlBe-GvPV86-riWShyVYpQPvm4iX0


###  GET TASK LISTS
GET {{baseUrl}}/tasklists 
content-type: application/json

### GET TASK LIST BY ID
GET {{baseUrl}}/tasklists/4
content-type: application/json

### CREATE TASKLIST
POST {{baseUrl}}/tasklists
content-type: application/json

{
	"title": "New Tasklist",
}

### UPDATE TASKLIST
PUT http://localhost:5000/api/tasklists/8
content-type: application/json

{
	"id": 8,
	"title": "3333333",
}

### DELETE TASKLIST
DELETE http://localhost:5000/api/tasklists/10


